name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        go: ['stable']
    steps:
      - uses: actions/checkout@v2

      # first download wasmtime's last static library build using python
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: python ci/download-wasmtime.py

      # then run our go tests ...
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go test -tags debug
      - run: go test -tags debug
        env:
          GODEBUG: cgocheck=2
          GOGC: 1
